name: flutter_base_structure_riverpod
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Fonts
  google_fonts: ^3.0.1

  bubble: ^1.2.1

  # Network
  dio: ^4.0.6

  # State Management
  flutter_riverpod: ^2.1.3

  # Page/Screen Navigator
  auto_route: ^5.0.1

  get: ^4.6.1
  get_it: ^7.2.0
  injectable: ^1.5.3

  animations: ^2.0.3

  dialog_service:
    git:
      url: https://github.com/CosmosExmo/dialog_service.git
      ref: e71cc459414494d925fb409ff2291de131ded035
  image_provider:
    git:
      url: https://github.com/CosmosExmo/image_provider.git
      ref: 1ef602fb595e72b006080ab4a51284d2b6256b5c
  focused_image_widget:
    git:
      url: https://github.com/CosmosExmo/focused_image_widget.git
  flare_flutter: ^3.0.2
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Generator Starter
  build_runner: ^2.1.5
  # Code Generators
  auto_route_generator: ^5.0.2
  injectable_generator: ^1.5.2

  # Lints
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
